# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: k8s-study
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      initContainers:
        - name: init-sleep
          image: busybox
          command: [ "sh", "-c" ]
          args:
            - echo "Sleeping for 5 seconds..."; sleep 5;
      containers:
      - name: spring-boot-app
        image: ${ECR_URL}:latest
        ports:
        - containerPort: 8080
